launcher: wordgen wordsearch pager
	gcc -o launcher launcher.c

wordgen:
	gcc -o wordgen wordgen.c

wordsearch:
	gcc -o wordsearch wordsearch.c

pager:
	gcc -o pager pager.c

clean:
	rm -rf wordgen wordsearch pager launcher
